version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget_checker_web
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget_checker_bot
    command: python run_bot.py  # Запуск скрипта бота
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      
  redis:
    image: redis:alpine
    container_name: budget_checker_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
